kind: Namespace
apiVersion: v1
metadata:
  name: aftermath-services
  labels:
    name: aftermath-services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: am-stats-legacy
  name: am-stats-legacy
  namespace: aftermath-services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: am-stats-legacy
  template:
    metadata:
      labels:
        app: am-stats-legacy
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "cloud.google.com/gke-nodepool"
                    operator: In
                    values:
                      - "spot-pool-1-cpu"
      tolerations:
        - key: high-cpu
          operator: Equal
          value: required
          effect: NoExecute
      imagePullSecrets:
        - name: regcred
      containers:
        - image: docker.io/vkouzin/am-stats-legacy:latest
          imagePullPolicy: Always
          name: am-stats-legacy
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
